import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import { UserContextProvider, useUser } from "@/providers/UserContext";
import SidebarServer from "@/components/sidebar/SidebarServer.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="flex">
          <UserContextProvider>
            <Sidebar />

            <div
              className={`flex flex-col flex-grow w-screen md:w-full min-h-screen overflow-visible ${inter.className}`}
            >
              {children}
            </div>
          </UserContextProvider>
        </div>
      </body>
    </html>
  );
}
